// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package org.haiyiyang.demo.proto;

public final class DemoContext {
  private DemoContext() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.haiyiyang.demo.proto.Context)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 agency_id = 1;</code>
     */
    int getAgencyId();

    /**
     * <code>string agency_name = 2;</code>
     */
    java.lang.String getAgencyName();
    /**
     * <code>string agency_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getAgencyNameBytes();
  }
  /**
   * Protobuf type {@code org.haiyiyang.demo.proto.Context}
   */
  public  static final class Context extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.haiyiyang.demo.proto.Context)
      ContextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Context.newBuilder() to construct.
    private Context(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Context() {
      agencyId_ = 0;
      agencyName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Context(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              agencyId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              agencyName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.haiyiyang.demo.proto.DemoContext.internal_static_org_haiyiyang_demo_proto_Context_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.haiyiyang.demo.proto.DemoContext.internal_static_org_haiyiyang_demo_proto_Context_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.haiyiyang.demo.proto.DemoContext.Context.class, org.haiyiyang.demo.proto.DemoContext.Context.Builder.class);
    }

    public static final int AGENCY_ID_FIELD_NUMBER = 1;
    private int agencyId_;
    /**
     * <code>int32 agency_id = 1;</code>
     */
    public int getAgencyId() {
      return agencyId_;
    }

    public static final int AGENCY_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object agencyName_;
    /**
     * <code>string agency_name = 2;</code>
     */
    public java.lang.String getAgencyName() {
      java.lang.Object ref = agencyName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agencyName_ = s;
        return s;
      }
    }
    /**
     * <code>string agency_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAgencyNameBytes() {
      java.lang.Object ref = agencyName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agencyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (agencyId_ != 0) {
        output.writeInt32(1, agencyId_);
      }
      if (!getAgencyNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, agencyName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (agencyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, agencyId_);
      }
      if (!getAgencyNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, agencyName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.haiyiyang.demo.proto.DemoContext.Context)) {
        return super.equals(obj);
      }
      org.haiyiyang.demo.proto.DemoContext.Context other = (org.haiyiyang.demo.proto.DemoContext.Context) obj;

      boolean result = true;
      result = result && (getAgencyId()
          == other.getAgencyId());
      result = result && getAgencyName()
          .equals(other.getAgencyName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGENCY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAgencyId();
      hash = (37 * hash) + AGENCY_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getAgencyName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.haiyiyang.demo.proto.DemoContext.Context parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.haiyiyang.demo.proto.DemoContext.Context parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.haiyiyang.demo.proto.DemoContext.Context parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.haiyiyang.demo.proto.DemoContext.Context parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.haiyiyang.demo.proto.DemoContext.Context parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.haiyiyang.demo.proto.DemoContext.Context parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.haiyiyang.demo.proto.DemoContext.Context parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.haiyiyang.demo.proto.DemoContext.Context parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.haiyiyang.demo.proto.DemoContext.Context parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.haiyiyang.demo.proto.DemoContext.Context parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.haiyiyang.demo.proto.DemoContext.Context parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.haiyiyang.demo.proto.DemoContext.Context parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.haiyiyang.demo.proto.DemoContext.Context prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.haiyiyang.demo.proto.Context}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.haiyiyang.demo.proto.Context)
        org.haiyiyang.demo.proto.DemoContext.ContextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.haiyiyang.demo.proto.DemoContext.internal_static_org_haiyiyang_demo_proto_Context_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.haiyiyang.demo.proto.DemoContext.internal_static_org_haiyiyang_demo_proto_Context_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.haiyiyang.demo.proto.DemoContext.Context.class, org.haiyiyang.demo.proto.DemoContext.Context.Builder.class);
      }

      // Construct using org.haiyiyang.demo.proto.DemoContext.Context.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        agencyId_ = 0;

        agencyName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.haiyiyang.demo.proto.DemoContext.internal_static_org_haiyiyang_demo_proto_Context_descriptor;
      }

      public org.haiyiyang.demo.proto.DemoContext.Context getDefaultInstanceForType() {
        return org.haiyiyang.demo.proto.DemoContext.Context.getDefaultInstance();
      }

      public org.haiyiyang.demo.proto.DemoContext.Context build() {
        org.haiyiyang.demo.proto.DemoContext.Context result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.haiyiyang.demo.proto.DemoContext.Context buildPartial() {
        org.haiyiyang.demo.proto.DemoContext.Context result = new org.haiyiyang.demo.proto.DemoContext.Context(this);
        result.agencyId_ = agencyId_;
        result.agencyName_ = agencyName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.haiyiyang.demo.proto.DemoContext.Context) {
          return mergeFrom((org.haiyiyang.demo.proto.DemoContext.Context)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.haiyiyang.demo.proto.DemoContext.Context other) {
        if (other == org.haiyiyang.demo.proto.DemoContext.Context.getDefaultInstance()) return this;
        if (other.getAgencyId() != 0) {
          setAgencyId(other.getAgencyId());
        }
        if (!other.getAgencyName().isEmpty()) {
          agencyName_ = other.agencyName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.haiyiyang.demo.proto.DemoContext.Context parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.haiyiyang.demo.proto.DemoContext.Context) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int agencyId_ ;
      /**
       * <code>int32 agency_id = 1;</code>
       */
      public int getAgencyId() {
        return agencyId_;
      }
      /**
       * <code>int32 agency_id = 1;</code>
       */
      public Builder setAgencyId(int value) {
        
        agencyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 agency_id = 1;</code>
       */
      public Builder clearAgencyId() {
        
        agencyId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object agencyName_ = "";
      /**
       * <code>string agency_name = 2;</code>
       */
      public java.lang.String getAgencyName() {
        java.lang.Object ref = agencyName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          agencyName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string agency_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAgencyNameBytes() {
        java.lang.Object ref = agencyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          agencyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string agency_name = 2;</code>
       */
      public Builder setAgencyName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        agencyName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string agency_name = 2;</code>
       */
      public Builder clearAgencyName() {
        
        agencyName_ = getDefaultInstance().getAgencyName();
        onChanged();
        return this;
      }
      /**
       * <code>string agency_name = 2;</code>
       */
      public Builder setAgencyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        agencyName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.haiyiyang.demo.proto.Context)
    }

    // @@protoc_insertion_point(class_scope:org.haiyiyang.demo.proto.Context)
    private static final org.haiyiyang.demo.proto.DemoContext.Context DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.haiyiyang.demo.proto.DemoContext.Context();
    }

    public static org.haiyiyang.demo.proto.DemoContext.Context getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Context>
        PARSER = new com.google.protobuf.AbstractParser<Context>() {
      public Context parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Context(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Context> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Context> getParserForType() {
      return PARSER;
    }

    public org.haiyiyang.demo.proto.DemoContext.Context getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_haiyiyang_demo_proto_Context_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_haiyiyang_demo_proto_Context_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcontext.proto\022\030org.haiyiyang.demo.prot" +
      "o\"1\n\007Context\022\021\n\tagency_id\030\001 \001(\005\022\023\n\013agenc" +
      "y_name\030\002 \001(\tB\rB\013DemoContextb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_haiyiyang_demo_proto_Context_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_haiyiyang_demo_proto_Context_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_haiyiyang_demo_proto_Context_descriptor,
        new java.lang.String[] { "AgencyId", "AgencyName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
